package com.szzt.emvtest.EMVSDK;

import com.ochafik.lang.jnaerator.runtime.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDK_RSA_PRIVATE_KEY extends Structure<SDK_RSA_PRIVATE_KEY, SDK_RSA_PRIVATE_KEY.ByValue, SDK_RSA_PRIVATE_KEY.ByReference > {
    /** length in bits of modulus */
    public int bits;
    /**
     * modulus<br>
     * C type : unsigned char[256ul]
     */
    public byte[] modulus = new byte[256];
    /**
     * public exponent<br>
     * C type : unsigned char[256ul]
     */
    public byte[] publicExponent = new byte[256];
    /**
     * private exponent<br>
     * C type : unsigned char[256ul]
     */
    public byte[] exponent = new byte[256];
    /**
     * prime factors<br>
     * C type : unsigned char[2][128ul]
     */
    public byte[] prime = new byte[((2) * (128))];
    /**
     * exponents for CRT<br>
     * C type : unsigned char[2][128ul]
     */
    public byte[] primeExponent = new byte[((2) * (128))];
    /**
     * CRT coefficient<br>
     * C type : unsigned char[128ul]
     */
    public byte[] coefficient = new byte[128];
    public SDK_RSA_PRIVATE_KEY() {
        super();
    }
    protected List<String> getFieldOrder() {
        return Arrays.asList("bits", "modulus", "publicExponent", "exponent", "prime", "primeExponent", "coefficient");
    }
    /**
     * @param bits length in bits of modulus<br>
     * @param modulus modulus<br>
     * C type : unsigned char[256ul]<br>
     * @param publicExponent public exponent<br>
     * C type : unsigned char[256ul]<br>
     * @param exponent private exponent<br>
     * C type : unsigned char[256ul]<br>
     * @param prime prime factors<br>
     * C type : unsigned char[2][128ul]<br>
     * @param primeExponent exponents for CRT<br>
     * C type : unsigned char[2][128ul]<br>
     * @param coefficient CRT coefficient<br>
     * C type : unsigned char[128ul]
     */
    public SDK_RSA_PRIVATE_KEY(int bits, byte modulus[], byte publicExponent[], byte exponent[], byte prime[], byte primeExponent[], byte coefficient[]) {
        super();
        this.bits = bits;
        if ((modulus.length != this.modulus.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.modulus = modulus;
        if ((publicExponent.length != this.publicExponent.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.publicExponent = publicExponent;
        if ((exponent.length != this.exponent.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.exponent = exponent;
        if ((prime.length != this.prime.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.prime = prime;
        if ((primeExponent.length != this.primeExponent.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.primeExponent = primeExponent;
        if ((coefficient.length != this.coefficient.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.coefficient = coefficient;
    }
    protected ByReference newByReference() { return new ByReference(); }
    protected ByValue newByValue() { return new ByValue(); }
    protected SDK_RSA_PRIVATE_KEY newInstance() { return new SDK_RSA_PRIVATE_KEY(); }
    public static SDK_RSA_PRIVATE_KEY[] newArray(int arrayLength) {
        return Structure.newArray(SDK_RSA_PRIVATE_KEY.class, arrayLength);
    }
    public static class ByReference extends SDK_RSA_PRIVATE_KEY implements Structure.ByReference {

    };
    public static class ByValue extends SDK_RSA_PRIVATE_KEY implements Structure.ByValue {

    };
}

