#ifndef SDKJCBPRIVATE_H
#define SDKJCBPRIVATE_H

typedef enum
{
	SDKJCB_TRANSFLOW_UNDEF_MODE=0,
	SDKJCB_TRANSFLOW_EMV_MODE,
	SDKJCB_TRANSFLOW_MSD_MODE,
	SDKJCB_TRANSFLOW_LEGACY_MODE,
}SDK_JCB_TRANSFLOW_MODE;


extern SDK_JCB_TRANSFLOW_MODE gstJCBTransFlowModeStatus;


#endif
